// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Class() {
  return window['go']['controller']['AppController']['Class']();
}

export function Detail(arg1) {
  return window['go']['controller']['AppController']['Detail'](arg1);
}

export function GetSourceList() {
  return window['go']['controller']['AppController']['GetSourceList']();
}

export function List(arg1) {
  return window['go']['controller']['AppController']['List'](arg1);
}

export function Search(arg1) {
  return window['go']['controller']['AppController']['Search'](arg1);
}

export function Setting(arg1) {
  return window['go']['controller']['AppController']['Setting'](arg1);
}
