// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Class():Promise<types.Response>;

export function Detail(arg1:types.DetailRequest):Promise<types.Response>;

export function GetSourceList():Promise<types.Response>;

export function List(arg1:types.ListRequest):Promise<types.Response>;

export function Search(arg1:types.SearchRequest):Promise<types.Response>;

export function Setting(arg1:types.SettingRequest):Promise<types.Response>;
